In [ ]:
"""##api key #https://www.youtube.com/watch?v=HOSGP23DAHI&list=PLKnIA16_RmvZAqJzKstVHywcRNMn6pcGD&index=2
06eaff9da8534cec42c0b86c180394e4
#send req 
https://api.themoviedb.org/3/movie/popular?api_key=<<api_key>>&language=en-US&page=1
we need a df of popularity vote count orgi lang title vote avg rel date 
shape of df 10000*7 cols"""

In [12]:
import requests
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [7]:
response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=06eaff9da8534cec42c0b86c180394e4&language=en-US&page=10').json() #response code 200

In [26]:
dict_response={}
popularity=[]
original_language=[]
title=[]
vote_average=[]
overview=[]
release_date=[]

In [30]:
for i in response['results']:
  title.append(i['title'])
  popularity.append(i['popularity'])
  original_language.append(i['original_language'])
  vote_average.append(i['vote_average'])
  release_date.append(i['release_date'])
  overview.append(i['overview'])
d={'title':title,'popularity':popularity,'original_language':original_language,'vote_average':vote_average,'release_date':release_date,'overview':overview}
df=pd.DataFrame(d)

In [ ]:
df.head()
df

In [39]:
final=pd.DataFrame()
for i in range(1,31):
  response=requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key=06eaff9da8534cec42c0b86c180394e4&language=en-US&page={i}').json() #response code 200
  for i in response['results']:
    title.append(i['title'])
    popularity.append(i['popularity'])
    original_language.append(i['original_language'])
    vote_average.append(i['vote_average'])
    release_date.append(i['release_date'])
    overview.append(i['overview'])
  d={'title':title,'popularity':popularity,'original_language':original_language,'vote_average':vote_average,'release_date':release_date,'overview':overview}
  df=pd.DataFrame(d)
  final=final.append(df,ignore_index=True)

In [40]:
final

,title,popularity,original_language,vote_average,release_date,overview
0,Transformers: Age of Extinction,130.009,en,5.9,2014-06-25,"As humanity picks up the pieces, following the..."
1,Sword Art Online the Movie -Progressive- Aria ...,140.347,ja,8.3,2021-10-30,One month after Kayaba Akihiko's game of death...
2,Addams Family Values,137.783,en,6.9,1993-11-19,Siblings Wednesday and Pugsley Addams will sto...
3,Office Invasion,119.172,en,5.8,2022-08-10,Three friends come together to defend their va...
4,Project Wolf Hunting,144.085,ko,6.7,2022-09-28,During transport from the Philippines to South...
...,...,...,...,...,...,...
31495,Bad Boys for Life,57.457,en,7.2,2020-01-15,Marcus and Mike are forced to confront new thr...
31496,The Party at Kitty and Stud's,53.470,en,3.1,1970-02-10,Kitty and Stud are lovers. They enjoy a robust...
31497,Purple Hearts,55.265,en,8.3,2022-07-29,An aspiring musician agrees to a marriage of c...
31498,The Consequences,58.565,es,4.8,2021-09-17,Since Fabiola saw her husband die in a diving ...
31499,Cinderella,70.554,en,7.0,1950-02-22,Cinderella has faith her dreams of a better li...